"""
generate_pdf_report.py
=======================
Builds a styled, multi-page executive PDF report
(`reports/Business_and_Technical_Report.pdf`) summarizing the Customer
Churn Prediction & Intelligent Retention System project, using reportlab's
Platypus layout engine.

Reads from models/:
    - model_comparison.csv
    - champion_model_info.json
    - top10_feature_importance.csv
(all produced by train_and_export.py or build_notebook.py)

so the report always reflects the latest trained model — no hard-coded numbers.

Run (from project root):
    python src/generate_pdf_report.py
"""

import json
import os

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    ListFlowable,
    ListItem,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

_SRC_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_SRC_DIR)

MODELS_DIR = os.path.join(_PROJECT_ROOT, "models")
REPORTS_DIR = os.path.join(_PROJECT_ROOT, "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

OUTPUT_PATH = os.path.join(REPORTS_DIR, "Business_and_Technical_Report.pdf")

# ---------------------------------------------------------------------
# Load supporting data (generated by train_and_export.py / build_notebook.py)
# ---------------------------------------------------------------------
comparison_df = pd.read_csv(os.path.join(MODELS_DIR, "model_comparison.csv"))
with open(os.path.join(MODELS_DIR, "champion_model_info.json")) as f:
    champion_info = json.load(f)
top10_importance = pd.read_csv(
    os.path.join(MODELS_DIR, "top10_feature_importance.csv"),
    header=None, names=["Feature", "Importance"], skiprows=1
)

champion_name = champion_info["champion_model"]
champion_metrics = champion_info["metrics"]

# ---------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------
NAVY = colors.HexColor("#1F3864")
ACCENT = colors.HexColor("#2E75B6")
LIGHT_GREY = colors.HexColor("#F2F2F2")

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(
    "ReportTitle", parent=styles["Title"], fontSize=24, textColor=NAVY,
    spaceAfter=6, alignment=TA_CENTER,
))
styles.add(ParagraphStyle(
    "ReportSubtitle", parent=styles["Normal"], fontSize=12,
    textColor=colors.HexColor("#595959"), alignment=TA_CENTER, spaceAfter=20,
))
styles.add(ParagraphStyle(
    "SectionHeading", parent=styles["Heading1"], fontSize=14.5, textColor=NAVY,
    spaceBefore=10, spaceAfter=6, borderPadding=0,
))
styles.add(ParagraphStyle(
    "SubHeading", parent=styles["Heading2"], fontSize=11.5, textColor=ACCENT,
    spaceBefore=8, spaceAfter=4,
))
styles.add(ParagraphStyle(
    "BodyJustify", parent=styles["Normal"], fontSize=9.7, leading=13.5,
    alignment=TA_JUSTIFY, spaceAfter=4,
))
styles.add(ParagraphStyle(
    "BulletText", parent=styles["Normal"], fontSize=10, leading=14, spaceAfter=4,
))
styles.add(ParagraphStyle(
    "Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey,
    alignment=TA_CENTER,
))


def section_divider():
    return HRFlowable(width="100%", thickness=1, color=colors.HexColor("#D9D9D9"),
                       spaceBefore=4, spaceAfter=10)


def make_metrics_table(df: pd.DataFrame) -> Table:
    header = list(df.columns)
    data = [header] + df.values.tolist()
    # Format floats
    for row in data[1:]:
        for i in range(1, len(row)):
            row[i] = f"{row[i]:.4f}" if isinstance(row[i], float) else row[i]

    table = Table(data, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#BFBFBF")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("TOPPADDING", (0, 0), (-1, -1), 3.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
    ]
    # Highlight champion row
    champ_row_idx = df.index[df["Model"] == champion_name].tolist()
    if champ_row_idx:
        r = champ_row_idx[0] + 1
        style.append(("BACKGROUND", (0, r), (-1, r), colors.HexColor("#D9E8F5")))
        style.append(("FONTNAME", (0, r), (-1, r), "Helvetica-Bold"))
    table.setStyle(TableStyle(style))
    return table


def make_feature_importance_table(df: pd.DataFrame) -> Table:
    data = [["Rank", "Feature", "Importance"]]
    for i, row in df.iterrows():
        data.append([str(i + 1), row["Feature"], f"{float(row['Importance']):.4f}"])
    table = Table(data, hAlign="CENTER", colWidths=[0.6 * inch, 3.6 * inch, 1.3 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (2, 0), (2, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#BFBFBF")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("TOPPADDING", (0, 0), (-1, -1), 2.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
    ]))
    return table


def bullets(items):
    return ListFlowable(
        [ListItem(Paragraph(t, styles["BulletText"]), leftIndent=6) for t in items],
        bulletType="bullet", start="circle", leftIndent=14, spaceBefore=2, spaceAfter=4,
    )


def footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(
        letter[0] / 2, 0.5 * inch,
        f"Customer Churn Prediction & Intelligent Retention System | Page {doc.page}",
    )
    canvas.restoreState()


# ---------------------------------------------------------------------
# Build the story (document content)
# ---------------------------------------------------------------------
story = []

# ===== PAGE 1: Executive Summary & Business Problem =====
story.append(Paragraph("Customer Churn Prediction &<br/>Intelligent Retention System", styles["ReportTitle"]))
story.append(Paragraph("Executive & Technical Report — Machine Learning Pipeline for Proactive Customer Retention", styles["ReportSubtitle"]))
story.append(section_divider())

story.append(Paragraph("Executive Summary", styles["SectionHeading"]))
story.append(Paragraph(
    "Customer churn — the loss of subscribers to competitors — is one of the most "
    "direct threats to recurring revenue in the telecommunications industry. This "
    "project delivers a complete, production-ready machine learning pipeline that "
    "identifies customers at high risk of churning before they leave, giving the "
    "business a window to intervene with targeted retention offers. Using the IBM "
    f"Telco Customer Churn dataset (7,043 customers, 21 attributes), we engineered "
    f"predictive features, benchmarked six modeling approaches, and selected "
    f"<b>{champion_name}</b> as the champion model, achieving a "
    f"<b>ROC-AUC of {champion_metrics['ROC-AUC']:.3f}</b> and "
    f"<b>Recall of {champion_metrics['Recall']:.1%}</b> on held-out test data — "
    "meaning the model correctly flags roughly 4 out of 5 customers who are about "
    "to churn.", styles["BodyJustify"],
))

story.append(Paragraph("Business Problem Statement", styles["SubHeading"]))
story.append(Paragraph(
    "The dataset shows an overall churn rate of approximately 26.5%, representing "
    "a substantial and continuous drain on recurring revenue. Acquiring a new "
    "customer is well documented to cost significantly more than retaining an "
    "existing one, making early identification of at-risk customers a "
    "high-leverage lever for improving profitability. Without a predictive system, "
    "retention efforts are either applied blanket-wide (expensive and inefficient) "
    "or reactively, after a customer has already decided to leave (too late to "
    "act). This project closes that gap by scoring every customer with a "
    "quantified churn probability, enabling the business to prioritize retention "
    "spend on the customers who need it most.", styles["BodyJustify"],
))

story.append(Paragraph("Key Business Findings", styles["SubHeading"]))
story.append(bullets([
    "Month-to-month contracts churn at far higher rates than one- or two-year contracts, "
    "identifying contract flexibility as the single largest churn lever.",
    "Churn risk is concentrated in the first 12 months of the customer lifecycle — "
    "the critical window for onboarding and early engagement.",
    "Customers paying via Electronic Check churn more than those on automatic "
    "payment methods, a proxy for lower commitment/engagement.",
    "Customers without add-on services (Online Security, Tech Support, etc.) churn "
    "more, suggesting these services increase switching costs and perceived value.",
    "High Monthly Charges combined with short tenure and month-to-month contracts "
    "defines the highest-risk customer segment in the portfolio.",
]))

# ===== Dataset & Methodology, Model Comparison (flows onto page 2) =====
story.append(Paragraph("Dataset & ML Methodology", styles["SectionHeading"]))
story.append(Paragraph(
    "<b>Dataset:</b> IBM Telco Customer Churn — 7,043 customers, 21 raw attributes "
    "spanning demographics, account information, and subscribed services. "
    "<b>Data Hygiene:</b> The <i>TotalCharges</i> field was coerced from string to "
    "numeric, with 11 blank-string records (all new customers with zero tenure) "
    "imputed to 0.", styles["BodyJustify"],
))
story.append(Paragraph(
    "<b>Feature Engineering:</b> Four new features were constructed to capture "
    "engagement and risk signals beyond the raw schema: "
    "<i>Total_Services_Used</i> (count of subscribed add-ons), "
    "<i>Estimated_LTV</i> (MonthlyCharges &times; tenure), "
    "<i>Tenure_Group</i> (lifecycle-stage bucket), and "
    "<i>Payment_Risk_Score</i> (flag for manual/non-automatic payment methods).",
    styles["BodyJustify"],
))
story.append(Paragraph(
    "<b>Preprocessing:</b> Binary target encoding (Churn), one-hot encoding for "
    "nominal categorical variables, standard scaling for continuous numeric "
    "features, and an 80/20 stratified train-test split (random_state=42) to "
    "preserve the class balance in both partitions.", styles["BodyJustify"],
))
story.append(Paragraph(
    "<b>Modeling:</b> A Logistic Regression baseline was benchmarked against "
    "Decision Tree, Random Forest, XGBoost, and SVM classifiers. Random Forest "
    "and XGBoost were further optimized via RandomizedSearchCV with 5-fold "
    "Stratified cross-validation, tuned for ROC-AUC.", styles["BodyJustify"],
))

story.append(Paragraph("Model Comparison", styles["SubHeading"]))
story.append(make_metrics_table(comparison_df))
story.append(Spacer(1, 6))
story.append(Paragraph(
    f"<i>The champion model ({champion_name}) is highlighted above, selected on "
    "the combination of ROC-AUC and Recall — the two metrics most aligned with "
    "the cost asymmetry of missed churners versus wasted retention offers "
    "(see Cost-Benefit discussion below).</i>", styles["BulletText"],
))

story.append(Spacer(1, 6))
story.append(KeepTogether([
    Paragraph("Top 10 Feature Importance Findings", styles["SubHeading"]),
    make_feature_importance_table(top10_importance),
    Spacer(1, 4),
    Paragraph(
        "Contract type dominates feature importance, followed by internet service "
        "type, tenure, and payment method — confirming that commitment structure and "
        "customer lifecycle stage are the primary churn drivers, ahead of "
        "demographic factors.", styles["BulletText"],
    ),
]))

story.append(Paragraph("Cost-Benefit Rationale: Why Recall & ROC-AUC", styles["SubHeading"]))
story.append(Paragraph(
    "A <b>False Positive</b> (flagging a loyal customer as a churn risk) costs the "
    "business a modest, bounded amount — an unnecessary discount or outreach call. "
    "A <b>False Negative</b> (missing an actual churner) costs the business the "
    "customer's full remaining lifetime value plus the higher expense of acquiring "
    "a replacement. Because missed churners are far more expensive than "
    "unnecessary offers, the pipeline prioritizes <b>Recall</b> — catching as many "
    "true churners as possible — while using <b>ROC-AUC</b> to select the model "
    "with the best overall ranking quality across all decision thresholds, rather "
    "than optimizing for raw Accuracy, which can be misleading on this "
    "moderately imbalanced (~26.5% churn) dataset.", styles["BodyJustify"],
))

# ===== Retention Strategies & Conclusion (flows onto page 3) =====
story.append(Spacer(1, 2))
story.append(Paragraph("5 Actionable Retention Strategies", styles["SectionHeading"]))

strategy_data = [
    ("1. Personalized Retention Offers",
     "Route customers with a churn probability above the high-risk threshold "
     "(e.g., 70%+) to a personalized save offer — a discount, plan credit, or "
     "service upgrade tailored to their usage pattern and current contract "
     "type — rather than a generic, one-size-fits-all promotion."),
    ("2. Loyalty & Contract Migration Rewards",
     "Since month-to-month customers churn at the highest rate, offer "
     "incentives (bill credits, free add-on trials) for migrating to one- or "
     "two-year contracts, directly targeting the single strongest churn driver "
     "identified by the model."),
    ("3. Early Churn Alert System",
     "Operationalize the model to score every customer monthly and trigger "
     "automated alerts to the retention team when a customer crosses into the "
     "medium- or high-risk band, enabling proactive outreach before the "
     "customer initiates a cancellation."),
    ("4. Engagement & Onboarding Campaigns",
     "Since churn risk peaks in the first 12 months, invest in a structured "
     "onboarding journey (welcome calls, usage tutorials, milestone check-ins) "
     "for new customers to build habitual engagement during the highest-risk "
     "window."),
    ("5. Service Upgrade & Bundling Incentives",
     "Customers without add-on services (Online Security, Tech Support, "
     "Device Protection) churn more; proactively offering bundled add-ons at a "
     "discount increases both switching costs and perceived value, "
     "particularly for high-Monthly-Charge fiber customers."),
]

for title, desc in strategy_data:
    story.append(Paragraph(title, styles["SubHeading"]))
    story.append(Paragraph(desc, styles["BodyJustify"]))

story.append(Spacer(1, 4))
story.append(Paragraph("Strategic Conclusion", styles["SectionHeading"]))
story.append(Paragraph(
    f"The {champion_name} model provides the business with a reliable, "
    f"quantified early-warning system for customer churn, correctly identifying "
    f"approximately {champion_metrics['Recall']:.0%} of at-risk customers before "
    "they leave. Deploying this model as an ongoing scoring service — paired with "
    "the five retention strategies above — creates a closed-loop system: "
    "predict risk, intervene proactively, and measure the resulting change in "
    "churn rate over time. Suggested next steps include A/B testing retention "
    "offers against model-identified risk segments, integrating the scoring "
    "pipeline into the CRM for real-time alerts, and periodically retraining the "
    "model as customer behavior and market conditions evolve.", styles["BodyJustify"],
))

story.append(Spacer(1, 8))
story.append(section_divider())
story.append(Paragraph(
    f"Report generated automatically from model artifacts (trained "
    f"{champion_info['trained_at']}). All metrics reflect performance on a held-out "
    "20% test set never seen during training or hyperparameter tuning.",
    styles["Footer"],
))

# ---------------------------------------------------------------------
# Build PDF
# ---------------------------------------------------------------------
doc = SimpleDocTemplate(
    OUTPUT_PATH, pagesize=letter,
    topMargin=0.75 * inch, bottomMargin=0.75 * inch,
    leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    title="Customer Churn Prediction - Business and Technical Report",
)
doc.build(story, onFirstPage=footer, onLaterPages=footer)

print(f"PDF report generated: {OUTPUT_PATH}")
